



--DROP TABLE ;
DROP TABLE RECURSO;
                

DROP TABLE NAVE;
DROP TABLE CONTRATO;
DROP TABLE CORPORACAO;
DROP TABLE GOVERNO;
DROP TABLE SATELITE;
DROP TABLE PLANETA;
DROP TABLE ASTEROIDE;
DROP TABLE CORPOPLANETARIO;
DROP TABLE ESTRELA;
DROP TABLE SISTEMA;
DROP TABLE CORPOCELESTE;